/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Producto;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import menu.GestorProductos;
import menu.PantallaProductos;
import menu.TablasConJava;

/**
 *
 * @author leonel
 */
public class MenuPantalla extends javax.swing.JFrame {
    public MenuPantalla()
    {
        super("Ejemplo de menú.");
        setSize(300, 300);
        GestorProductos gestorProductos = new GestorProductos();
        
        JMenu fileMenu = new JMenu("File");
        JMenuItem productos = new JMenuItem("Productos");
        //JLabel texto = new JLabel();

        productos.setMnemonic('N');
        fileMenu.add(productos);

        productos.addActionListener
        (new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    PantallaProductos pantallaProductos = new PantallaProductos(gestorProductos);
                    pantallaProductos.setVisible(true);
                }
            }
        );

        JMenuItem salir = new JMenuItem("Exit");
        salir.setMnemonic('E');
        fileMenu.add(salir);
        
        salir.addActionListener
        (
            new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    System.exit(0);
                }
            }
        );
        
        JMenuItem mostrar = new JMenuItem("Mostrar");
        mostrar.setMnemonic('M');
        fileMenu.add(mostrar);
        
        mostrar.addActionListener
        (
            new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    //JOptionPane.showMessageDialog(null,informe);
                    TablasConJava.run(gestorProductos);
                }
            }
        );
        
        JMenuBar barra = new JMenuBar();
        barra.add(fileMenu);
        setJMenuBar(barra);
        getContentPane().setBackground(Color.DARK_GRAY);
        
        setJMenuBar(barra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}